var = input('DIGITE ALGO: ')
print('Tipo primitivo: {}'.format(type(var)))
print('Só tem espaços? {}'.format(var.isspace()))
print('É um número? {}'.format(var.isnumeric()))
print('É alfabetico? {}'.format(var.isalpha()))
print('É alfanumerico? {}'.format(var.isalnum()))
print('Está em maiúsculas? {}'.format(var.isupper()))
print('Está em minúsculas? {}'.format(var.islower()))
print('Está capitalizada? {}'.format(var.istitle()))